### ISSUE TITLE
Support for unicode characters in a lumrest scenario?

### ISSUE THREAD

**Issue by nilleb** [lumapps/lumRest#25]
```
DEBUG	05.612[base_handler.py.dispatch:198] Request / generated in 9.962 sec
INFO     2017-03-17 10:37:05,635 module.py:806] default: "GET / HTTP/1.1" 302 -
INFO     2017-03-17 10:37:06,132 module.py:806] default: "GET /_ah/api/discovery/v1/apis/lumsites/v1/rest HTTP/1.1" 200 591642
stty: standard input: Inappropriate ioctl for device
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/Lumapps - LumSites - Pull Requests CI/lumRest/lumrest.py", line 58, in <module>
    sys.exit(main())
  File "/var/lib/jenkins/workspace/Lumapps - LumSites - Pull Requests CI/lumRest/lumrest.py", line 36, in main
    scene = yaml.load(scene_file)
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 474, in parse_flow_sequence_first_entry
    return self.parse_flow_sequence_entry(first=True)
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 477, in parse_flow_sequence_entry
    if not self.check_token(FlowSequenceEndToken):
  File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 248, in fetch_more_tokens
    return self.fetch_double()
  File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 652, in fetch_double
    self.fetch_flow_scalar(style='"')
  File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 663, in fetch_flow_scalar
    self.tokens.append(self.scan_flow_scalar(style))
  File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 1152, in scan_flow_scalar
    chunks.extend(self.scan_flow_scalar_non_spaces(double, start_mark))
  File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 1192, in scan_flow_scalar_non_spaces
    while self.peek(length) not in u'\'\"\\\0 \t\r\n\x85\u2028\u2029':
  File "/usr/lib/python2.7/dist-packages/yaml/reader.py", line 91, in peek
    self.update(index+1)
  File "/usr/lib/python2.7/dist-packages/yaml/reader.py", line 169, in update
    self.check_printable(data)
  File "/usr/lib/python2.7/dist-packages/yaml/reader.py", line 144, in check_printable
    'unicode', "special characters are not allowed")
yaml.reader.ReaderError: unacceptable character #x1f641: special characters are not allowed
  in "/var/lib/jenkins/workspace/Lumapps - LumSites - Pull Requests CI/tests/user/tmp.yaml", position 5535
  FAIL (24 seconds) user/user_search.yaml
```

**Comment by despatates** [comment]
Hi @nilleb ,
Can you give us the scenario you used to get this error?
Thanks.

**Comment by nilleb** [comment]
```
Executing : user.list
Description: Get a list of users by ids and invalid firstname, should return an empty list
```

**Comment by despatates** [comment]
```yaml
- user.directory.list:
    body: {profileCriteria: {'name.firstName': "éàëêàç☹️🙁😠😡😞😟😣😖日本語"}}
  description: Search user with accent in directory
  config:
    auth:
      email: "admin@example.com"
  check_result: { items: nil }
```

**Comment by despatates** [comment]
@nilleb 
Not reproduced on dev environment, not reproduced on a new build on remote env.
